### ISSUE TITLE
Adding to the demos section

### ISSUE THREAD

**Issue by vipulgupta2048** [CuriousLearner/git-intro#5]
- I think the demos section can be expanded into their commands and description. People tend to understand more if the commands are on screen with a "small different than Wikipedia" definition.  
- I have made a similar presentation with a detailed command list which a person can refer to order-wise, helping the viewers understand one by one.  
  
Referring to link - https://docs.google.com/presentation/d/1dLshLydrBL8t_X3nvOodi-LkH8iORocy8uadGrlslGc/edit?usp=sharing

**Comment by CuriousLearner** [comment]
Yes, the details are needed. When these slides were made, I didn't have enough time to work on them & since then the demo section wasn't expanded in slides form and remained a hands-on session.

It would be good to expand it in separate slides. Would you like to work on it? Feel free to issue a PR.
